[ENTER]
# Абсолютный путь к папке, где находится репозиторий `enter`.
# Этот путь используется для доступа к файлам и папкам проекта.
# Пример: /home/user/.local/bin/enter
home = /path/to/enter_folder

# Абсолютный путь к YAML-файлу, содержащему конфигурацию алиасов.
# Этот файл обычно содержит набор сокращений (алиасов) для команд,
# которые упрощают работу с инструментами или скриптами.
# Пример: /home/user/aliases.yml
yaml_file_path = /path/to/aliases.yml