[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "enter"
description = "Manager of aliases and scripts for being and automation"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
authors = [
    { name = "Adam Morington", email = "morington.mail@gmail.com" },
]
maintainers = [
    { name = "Adam Morington", email = "morington.mail@gmail.com" },
]
keywords = [
    "alias",
    "script",
    "manager",
    "automation",
    "terminal",
    "cli",
    "workflow",
    "commands",
    "integration"
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Operating System :: Microsoft :: Windows",
    "Topic :: System :: Shells",
    "Topic :: Utilities",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Automation",

]
dependencies = [
    "PyYAML>=6.0.2",
    "structlog>=25.1.0"
]
dynamic = ["version"]

[tool.hatch.version]
path = "enter/__meta__.py"

[project.urls]
#Homepage = ""
#Documentation = ""
Repository = "https://github.com/morington/enter/"

[tool.ruff.lint]
select = [
    "C4",
    "E",
    "F",
    "T10",
    "T20",
    "Q",
    "RET",
]
ignore = [
    "E501",
    "F401",
    "T201"
]
exclude = [
    "tests/",
    "**/__pycache__",
    "examples/*",
    "dev/*"
]
